services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: popmashup-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YOUR_STRONG_SA_PASSWORD_HERE
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -C -Q \"SELECT 1\" || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: PopCultureMashup.Api/Dockerfile
    container_name: popmashup-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PopCultureMashup;User Id=sa;Password=YOUR_STRONG_SA_PASSWORD_HERE;TrustServerCertificate=True;Encrypt=False;
      - External__Rawg__ApiKey=YOUR_RAWG_API_KEY_HERE
      - Jwt__Key=YOUR_JWT_SECRET_KEY_HERE
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mssql_data:
    driver: local
